sources:
  - name: raw
    description: Raw data from CSV files
    database: postgres
    schema: raw

    tables:
      - name: listings
      - name: census_g01
      - name: census_g02
      - name: nsw_lga_code
      - name: nsw_lga_suburb